version: '3'
services:
  larateapi:
    mem_limit: ${APP_MEM_LIMIT}
    container_name: ${APP_NAME}-api
    restart: 'always'
    build:
      context: "./"
      dockerfile: "Dockerfile"
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT2}:443
      - ${APP_DEV_PORT}:5173
    links:
      - laratedatabase
    volumes:
       - ./root/laravel:/var/www/html
       - ./docker/domain:/etc/apache2/sites-enabled
  laratedatabase:
    mem_limit: ${MYSQL_MEM_LIMIT}
    container_name: ${APP_NAME}-databas 
    restart: 'always'
    build:
      context: "./docker/mysql"
      dockerfile: "Dockerfile"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      #- ./docker/mysql/conf.d/my.cnf:/etc/my.cnf
      - ./docker/logs:/var/log/mysql
    ports:
      - ${MYSQL_ROOT_PORT}:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=cms2023
      - MYSQL_USER=cms2023
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
  laratephpmyadmin:
    mem_limit: ${PHPMYADMIN_MEM_LIMIT}
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin:latest 
    restart: 'always'
    links:
      - laratedatabase
    ports: 
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=laratedatabase
  laratemail:
    container_name: ${APP_NAME}-mail 
    restart: 'always'
    image: mailhog/mailhog
    mem_limit: 64m
    ports:
      - ${MAIL_PORT_PANEL_PORT}:1025    
      - ${MAIL_PORT_PORT}:8025
    
